ruleName: kafka
sqlQuery:
  sql: family == "kafka"
  params: {}
celQuery: family == "kafka"
timeframeInSeconds: 10800
timeUnit: seconds
groupingCriteria:
- zone
- cluster
- alertname
resolveOn: all_resolved
createOn: any
incidentNameTemplate: '{{ alert.cluster }}: {{ alert.alertname }}'
requireApprove: false
threshold: 1
